import Head from "next/head";
import Image from "next/image";
import Navbar from "@/components/Layout/Navbar";
import Footer from "@/components/Layout/Footer";
import CarCard from "@/components/HomePage/CarCard";
import Landing from "@/components/HomePage/Landing";
import Carousel from "@/components/HomePage/Carousel";

export default function Home() {
  return (
    <>
      <Head>
        <title>Car Max | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="homepage">
        <Navbar />
        {/* <Carousel /> */}
        <Landing/>
        <div className="car-display">
          <h1>Browse From Our Massive car Collection</h1>
          <div className="car-card">
            <CarCard />
            <CarCard />
            <CarCard />
            <CarCard />
            <CarCard />
            <CarCard />
            <CarCard />
            <CarCard />
            <CarCard />
            <CarCard />
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
}
