import Head from 'next/head'
import Navbar from '@/components/Layout/Navbar'
import Image from 'next/image'
export default function Home() {
  return (
    <>
      <Head>
        <title>Car Max | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='homepage'>
        <Navbar/>
      </div>
          </>
  )
}
