import Head from "next/head";
import Image from "next/image";
import Navbar from "@/components/Layout/Navbar";
import Footer from "@/components/Layout/Footer";
import { ThemeContext } from "@/context/Context";
import { useState, useEffect, useRef } from "react";
import CarCard from "@/components/HomePage/CarCard";
import Landing from "@/components/HomePage/Landing";
import Carousel from "@/components/HomePage/Carousel";

export default function Home() {
  const storage = typeof window !== "undefined" ? localStorage.theme: 'light'
  const [theme, setTheme] = useState(storage);

  useEffect(() => {
    if (localStorage.getItem('theme') !== theme) {
      const setString = JSON.stringify(theme);
      window.localStorage.setItem("theme", setString);
    }
  }, [ theme ]);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const getString = window.localStorage.getItem("theme");
      if (getString !== null) {
      const state = JSON.parse(getString);
      setTheme(state)
      }
    }
  }, [theme]);
  
  const toggleTheme = () => {
    setTheme((state:string) => (state === "light" ? "dark" : "light"));
  };

  return (
    <div id={theme}>
      <Head>
        <title>Car Max | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <ThemeContext.Provider value={{ theme, toggleTheme}}>
      <div className="homepage">
        <Navbar />
        {/* <Carousel /> */}
        <Landing/>
        <div className="car-display">
          <h1>Browse From Our Massive car Collection</h1>
          <div className="car-card">
            <CarCard />
          </div>
        </div>
        <Footer />
      </div>
      </ThemeContext.Provider>
    </div>
  );
}